Repository salvarez14/CodeGuardFront, pull requests merged in 2024-11, with the labels that each got.

#1 Creation of main page
  angular.json
  package-lock.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/header/header.component.css
  src/app/header/header.component.html
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/styles.css
Labels: component, home, header

#3 Creation of error component
  src/app/app.routes.ts
  src/app/error/error.component.css
  src/app/error/error.component.html
  src/app/error/error.component.spec.ts
  src/app/error/error.component.ts
  src/app/header/header.component.css
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/home/home.component.html
  src/app/register/register.component.ts
Labels: component

#5 Feature user profile component
  src/app/app.routes.ts
  src/app/error/error.component.css
  src/app/header/header.component.html
  src/app/model/exercise-response.ts
  src/app/model/user-info.ts
  src/app/personalpage/personalpage.component.css
  src/app/personalpage/personalpage.component.html
  src/app/personalpage/personalpage.component.spec.ts
  src/app/personalpage/personalpage.component.ts
  src/app/service/exercise.service.spec.ts
  src/app/service/exercise.service.ts
  src/app/service/user.service.ts
Labels: component

#6 Creation of exercise component
  src/app/app.routes.ts
  src/app/exerciselist/exerciselist.component.css
  src/app/exerciselist/exerciselist.component.html
  src/app/exerciselist/exerciselist.component.spec.ts
  src/app/exerciselist/exerciselist.component.ts
  src/app/exercisepage/exercisepage.component.css
  src/app/exercisepage/exercisepage.component.html
  src/app/exercisepage/exercisepage.component.spec.ts
  src/app/exercisepage/exercisepage.component.ts
  src/app/header/header.component.html
  src/app/model/exercise-response.ts
  src/app/model/user-info.ts
  src/app/personalpage/personalpage.component.css
  src/app/personalpage/personalpage.component.html
  src/app/personalpage/personalpage.component.ts
  src/app/service/exercise.service.ts
Labels: component

#7 Creation of solutions component for exercise personal page
  src/app/app.routes.ts
  src/app/exercisepage/exercisepage.component.css
  src/app/exercisepage/exercisepage.component.html
  src/app/exercisepage/exercisepage.component.ts
  src/app/exercisepagesolutions/exercisepagesolutions.component.css
  src/app/exercisepagesolutions/exercisepagesolutions.component.html
  src/app/exercisepagesolutions/exercisepagesolutions.component.spec.ts
  src/app/exercisepagesolutions/exercisepagesolutions.component.ts
  src/app/model/solutions-response.ts
  src/app/service/solutions.service.spec.ts
  src/app/service/solutions.service.ts
Labels: component

#9 Feature tests personal page component
  src/app/model/compiler-test-request.ts
  src/app/service/compiler.service.ts
  src/app/testpage/testpage.component.css
  src/app/testpage/testpage.component.html
  src/app/testpage/testpage.component.spec.ts
  src/app/testpage/testpage.component.ts
Labels: component, tests

#10 Feature tests component
  src/app/app.routes.ts
  src/app/header/header.component.html
  src/app/model/compiler-test-request.ts
  src/app/service/compiler.service.ts
  src/app/testpage/testpage.component.css
  src/app/testpage/testpage.component.html
  src/app/testpage/testpage.component.spec.ts
  src/app/testpage/testpage.component.ts
  src/app/testslist/testslist.component.css
  src/app/testslist/testslist.component.html
  src/app/testslist/testslist.component.spec.ts
  src/app/testslist/testslist.component.ts
Labels: component, tests

#12 Front end Error managing feature
  src/app/environment.ts
  src/app/error/error.component.ts
  src/app/exerciselist/exerciselist.component.ts
  src/app/exercisepage/exercisepage.component.css
  src/app/exercisepage/exercisepage.component.ts
  src/app/exercisepagesolutions/exercisepagesolutions.component.ts
  src/app/header/header.component.css
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/login/login.component.ts
  src/app/model/error-message.ts
  src/app/personalpage/personalpage.component.ts
  src/app/service/auth.service.ts
  src/app/service/compiler.service.ts
  src/app/service/error.service.spec.ts
  src/app/service/error.service.ts
  src/app/service/exercise.service.ts
  src/app/service/solutions.service.ts
  src/app/service/user.service.ts
  src/app/testpage/testpage.component.ts
  src/app/testslist/testslist.component.ts
  src/app/userpage/userpage.component.ts
Labels: component

#13 Feature creation exercise component
  src/app/app.routes.ts
  src/app/creationexercise/creationexercise.component.css
  src/app/creationexercise/creationexercise.component.html
  src/app/creationexercise/creationexercise.component.spec.ts
  src/app/creationexercise/creationexercise.component.ts
  src/app/header/header.component.html
  src/app/model/create-exercise-request.ts
  src/app/service/exercise.service.ts
  src/app/testpage/testpage.component.spec.ts
  src/app/testslist/testslist.component.spec.ts
Labels: bug, component, creationexercise
